# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesAll <- function(x) {
    .Call(`_header_reprex_timesAll`, x)
}

timesThree <- function(x) {
    .Call(`_header_reprex_timesThree`, x)
}

timesTwo <- function(x) {
    .Call(`_header_reprex_timesTwo`, x)
}

